const CONFIG = {
    titleWeb: " Đừng có cười tui á :(((",
    introTitle: ' Thảo My So Yummy',
    introDesc: ` chuyên mục hỏi đáp cùng Phúc Lê xin được phép bắt đầu:)))`,
    btnIntro: 'Ấn vào đây đi bé:3',
    title: 'Ấn tượng đầu tiên khi bà nhắn tin với tui là gì dạaa?🥰',
    desc: ' chắc là thấy tui hiền lạnh tốt bụng hennn ',
    btnYes: ' đúng rùiiii á ><',
    btnNo: 'Không nha :3',
    question: ' Thế ngoài hiền lành ra bà còn ấn tượng gì ở tui hong .-.?',
    btnReply: 'Gửi cho bạn <3',
    reply: ' chắc là thấy ông đẹp trai óoo:)',
    mess: 'Mình biết mà 🥰. Kẻm ơn bạn nhiều nhiều 😘😘',
    messDesc: '     Khi vô đây nhớ đi chơi với tui đóoo.',
    btnAccept: 'Okiiiii lun <3',
}
